[package]
name = "ircc-ai"
version = "0.1.0"
edition = "2021"
description = "A simple IRCC generative AI chatbot"
readme = "README.md"
repository = "https://github.com/EtaCassiopeia/ircc-ai"
authors = ["Mohsen Zainalpour <zainalpour@yahoo.com>"]
license = "MIT"

default-run = "indexer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "indexer"
path = "src/bin/indexer.rs"

[dependencies]
anyhow = "1.0.75"
async-recursion = "1.0.5"
clap = { version = "4.4.6", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
log = "0.4.20"
tokio = {version = "1.32.0",  features = ["full"] }

